spring:
  application:
    name: apollo-adminservice
  profiles:
    active: @profileActive@

ctrip:
  appid: 100003172

server:
  port: 8090

logging:
  file: /opt/logs/100003172/apollo-adminservice.log
